### ISSUE TITLE
passed: key on a get resource does not render visually as a dependency

### ISSUE THREAD

**Issue by jayhancock** [spring-projects/atom-concourse#6] opened 2019-01-08 00:15 UTC
When two jobs are defined, and the second job triggers with a `passed: [previous-job-name]` key, the plugin does not render that properly.

For example:
https://concoursetutorial.com/basics/pipeline-jobs/ renders as:
![image](https://user-images.githubusercontent.com/57141/50800876-e148e500-12a7-11e9-97df-f435a478bc35.png)

But in the atom preview, renders as:
![image](https://user-images.githubusercontent.com/57141/50800897-ff164a00-12a7-11e9-8073-6034cdbf7d9e.png)

The pipeline file to recreate this issue is found at:
https://github.com/starkandwayne/concourse-tutorial/blob/master/tutorials/basic/pipeline-jobs/pipeline.yml

**Comment by BoykoAlex** [comment] 2019-01-08 00:32
@jayhancock hmm... if you're concerned about the rendering of a particular concourse pipeline yml file than maybe you should raise an issue against concourse UI... This repo is the release repo for Atom extension for editing Concourse pipeline and task yml files... i.e. content assist, hover content over keywords in the concourse yml files etc...
Are you sure the problem is with the yml files editor rather than concourse web UI?
(In case of web UI issue the repo is https://github.com/concourse/concourse)

**Comment by kdvolder** [comment] 2019-01-08 23:18
@BoykoAlex  I think @jayhancock is talking about an atom extension that show a visual  'preview' of the pipeline. 

He says:

> But in the atom preview, ....

I've heard about such a extension and even tried it out a bit in the past.

@jayhancock The repository here, where you filed the bug is not that extension. This repository only provides editor support, as Alex explained.

I'm not sure which extension you installed but I guess probably it is this one:

https://atom.io/packages/concourse-vis

Their github repo is here:  https://github.com/danhigham/concourse-vis

I'll close this ticket as I don't think you are actually reporting a bug in *our* extension :-)

**Closed as completed by kdvolder** 2019-01-08 23:18 UTC
